### ISSUE TITLE
[Re] A general model of hippocampal and dorsal striatal learning and decision making

### ISSUE THREAD

**Issue by thomasMisiek** [ReScience/submissions#62]
**Original article:** Geerts, J. P., Chersi, F., Stachenfeld, K. L., & Burgess, N. (2020). A general model of hippocampal and dorsal striatal learning and decision making. In Proceedings of the National Academy of Sciences (Vol. 117, Issue 49, pp. 31427–31437). Proceedings of the National Academy of Sciences. https://doi.org/10.1073/pnas.2007981117

**PDF URL:** https://github.com/thomasMisiek/A-general-model-of-hippocampal-and-dorsal-striatal-learning-and-decision-making/blob/main/article.pdf
**Metadata URL:** https://github.com/thomasMisiek/A-general-model-of-hippocampal-and-dorsal-striatal-learning-and-decision-making/blob/main/metadata.tex
**Code URL:** https://github.com/thomasMisiek/mixed-coordination-models

**Scientific domain: **Computational Neuroscience, Spatial Navigation
**Programming language:** Python, Jupyter Notebook
**Suggested editor:**

**Comment by rougier** [comment]
Thanks for your submission. I'll edit it.

@vitay @mstimberg  Coudl you review this submission?

**Comment by vitay** [comment]
Yes. 

> In can take up to one week to be computed on a laptop (i5 2.30ghz), if the RTDP algorithm is used as the HPC model, and roughly 2 days if the SR is selected.

But do not expect my review for tomorrow, then...

**Comment by rougier** [comment]
@vitay Any time will do, thanks.

**Comment by thomasMisiek** [comment]
Thank you very much for your time ! @vitay if that may help you, only the SR was used in this work, the RTDP model was used for another project.

**Comment by mstimberg** [comment]
@rougier Thanks for the invite, I'd be happy to review the submission. But just to make sure that the effort is well spent: is it a problem that the original article already comes with reproducible [code on ModelDB](https://senselab.med.yale.edu/ModelDB/showmodel.cshtml?model=266836)? I vaguely remember discussions that submissions for papers with published and accessible code are only appropriate for ReScience C if the replication is a "clean room" implementation, which is clearly not the case here, given the statement in the [README](https://github.com/thomasMisiek/mixed-coordination-models/blob/main/README.md):
> Numerous classes, functions and methods in this work are partially or fully taken from Geerts, Chersi, Stachenfeld and Burgess (2020) original code.

I did not find anything about this in the ReScience FAQ and it is of course possible that I remember this discussion incorrectly.

**Comment by rougier** [comment]
@mstimberg Oh thank for noticing, I did not check it.
@thomasMisiek Can you explain what is your personal work exactly (and if this is a replication or a reproduction)?

**Comment by vitay** [comment]
A good deal of the pdf is about that. In short, the code provided by Geerts et al does not allow to reproduce the results of their paper without changing the parameters, nor does it allow to reproduce the original experiments of Pearce et al without changing some critical part of the code. I have not looked in detail yet what the contribution is in terms of lines of code, but functionally this makes sense to me. It is actually both a reproduction of Geerts' paper and a replication of Pearce's experiment (or the opposite?).
I think their approach is valid, but yes, we should discuss it beforehand.

**Comment by vitay** [comment]
A note on installation: with an empty environment (only python, pip and wheel), pip-installing requirements.txt fails as some dependencies need numpy to compile themselves, but it is not installed yet. I created a conda yaml file instead:

```yaml
name: mixedcoord
channels:
  - conda-forge
dependencies:
  - python=3.9.9
  - ipython=8.0.0
  - matplotlib=3.5.1
  - numpy=1.22.0
  - pandas=1.3.5
  - patsy=0.5.2
  - scikit-image=0.19.1
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - seaborn=0.11.2
  - statsmodels=0.13.1
 ```

I had to upgrade most packages to their last version, as the earlier versions declared in the pipfile did not support osx arm64 architectures. I had apparently no issue when running perform_full_rodrigo.py with best_geerts, but I have not visualized anything yet. 

@thomasMisiek Perhaps you can check that these versions still work for you and ship the yaml file with your repo?

```bash
conda env create -f environment.yml
```

**Comment by thomasMisiek** [comment]
@rougier Sure. My initial work consisted in comparing the biological plausibility of two models of rats' spatial navigation behavior (Geerts et al, 2020, Dollé et al 2010). For this initial project, we decided to use Geerts' original code as the basis of our future implementations, as it already provided the implementation of one of the task we wanted to simulate (Pearce et al, 1998) as well as the navigation model itself. 

However, while becoming familiar with Geerts and colleagues code, we found several discrepancies between their simulated protocol and the experimental protocol of Pearce et al (1998). After correcting the protocol, we found that Geerts' model and its original parameters were no longer able to replicate the experimental data. Thus, we created and performed a custom parameter optimization process to check if any new set of parameters was able to replicate Pearce et al, (1998) results. We found that there indeed was such a set of parameters, hence the theoretical model of Geerts was validated even if we initially found that the implementation was faulty. 

We argue that the simulated protocol was sufficiently modified for our article to be considered a **replication** of the phenomena observed in Pearce's article rather than a simple reproduction of Geerts' results. This is supported by the fact that Geerts model was initially not able to perform well on the new protocol. Nevertheless, we also provide in the article a separate and successful **reproduction** of Geerts' results with the non-modified protocol. 

Finally we can argue that our modified code is also less computationally expensive than the original one, with 25min against 4h30 for 100 agents simulation on Pearce experiment (2 days was only for the parameters optimization process, which we published the results of in the paper). We can also argue that our code is documented, with a functional directory-tree and original notebooks that allows the user to easily visualize extensive results. Moreover, we provide supplementary experiments and spatial cognition models in our implementation, since our Github repository is shared between two related articles. These new models and tasks required refactorisation of the code, and thus brought additional **technical** modifications, which further plead for a replication and not a reproduction according to the ReScience FAQ. Overall these enhancements and modifications prompted us to publish our code, which we believe is an interesting additional option to simulate Geerts' model, beside the ModelDB's one.

**Comment by thomasMisiek** [comment]
@vitay Thanks for this ! I will check and update the repository if it works.

**Comment by MehdiKhamassi** [comment]
In addition to what @thomasMisiek described, when he writes "Nevertheless, we also provide in the article a separate and successful reproduction of Geerts' results with the non-modified protocol.", we can add that even for this reproduction, we had to search for the correct model parameters. This is because the value of a few model parameters were not specified in the paper, and a few other parameters were indicated as having different values than what we found in the original code. So @thomasMisiek had to perform a parameter search to do this reproduction.
We have included a table in our manuscript which specifies what are the correct parameter values for each results figure.

**Comment by thomasMisiek** [comment]
I added the environment.yml file to the repository, added a few lines about it in the README. I kept the requirements.txt file as another option but updated it.

**Comment by rougier** [comment]
@MehdiKhamassi @thomasMisiek Sorry for late answer. I think it makes sense to keep it as a replication then. @vitay @mstimberg you can proceed with review.

**Comment by mstimberg** [comment]
@thomasMisiek I started to work on the review and was about to run the code, but just noticed that the `GEERTS-hippocampus-dls-modified` directory which is supposed to contain the code for the reproduction  is empty. I think it is supposed to be a git submodule, but it does not seem to be pointing anywhere.

**Comment by thomasMisiek** [comment]
@mstimberg Right, I fixed it. There was a conflict with the submodule. The content of the directory is now accessible.

**Comment by vitay** [comment]
@thomasMisiek I finally ran the notebook `Geerts Arbitrator - Egocentric MF-SR.ipynb` (15 hours for the two grid searches...). Unfortunately, when running the cell with:

```python
res_df = plot_all_perfs(path, size_plot=10, relative=True)
```

I got the following error: 

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~/Applications/miniforge3/envs/mixedcoord/lib/python3.9/site-packages/pandas/core/indexes/base.py:3361, in Index.get_loc(self, key, method, tolerance)
   [3360](file:///~/Applications/miniforge3/envs/mixedcoord/lib/python3.9/site-packages/pandas/core/indexes/base.py?line=3359)[ try:
-> ]()[3361](file:///~/Applications/miniforge3/envs/mixedcoord/lib/python3.9/site-packages/pandas/core/indexes/base.py?line=3360)[     return self._engine.get_loc(casted_key)
   ]()[3362](file:///~/Applications/miniforge3/envs/mixedcoord/lib/python3.9/site-packages/pandas/core/indexes/base.py?line=3361)[ except KeyError as err:

File ~/Applications/miniforge3/envs/mixedcoord/lib/python3.9/site-packages/pandas/_libs/index.pyx:76, in pandas._libs.index.IndexEngine.get_loc()

File ~/Applications/miniforge3/envs/mixedcoord/lib/python3.9/site-packages/pandas/_libs/index.pyx:108, in pandas._libs.index.IndexEngine.get_loc()

File pandas/_libs/hashtable_class_helper.pxi:5198, in pandas._libs.hashtable.PyObjectHashTable.get_item()

File pandas/_libs/hashtable_class_helper.pxi:5206, in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'se_cluster_100_rodrigo_mean_relative'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
/Users/vitay/Articles/reviews/ReScience-Misiek/sources/notebooks/Geerts Arbitrator - Egocentric MF-SR.ipynb Cell 19' in <module>
----> ]()[1](vscode-notebook-cell:/Users/vitay/Articles/reviews/ReScience-Misiek/sources/notebooks/Geerts%20Arbitrator%20-%20Egocentric%20MF-SR.ipynb#ch0000018?line=0)[ res_df = plot_all_perfs(path, size_plot=10, relative=True)

File ~/Articles/reviews/ReScience-Misiek/sources/grid_search.py:939, in plot_all_perfs(directory, size_plot, relative, mode)
    ]()[936](file:///~/Articles/reviews/ReScience-Misiek/sources/grid_search.py?line=935)[ df_pearce,data1,bin12,bin11 = plot_single_perfs(res_df, size_plot, "inv_temp", "srlr", "pearce", relative)
    ]()[937](file:///~/Articles/reviews/ReScience-Misiek/sources/grid_search.py?line=936)[ _,data4,bin42,bin41 = plot_single_perfs(res_df, size_plot, "qlr", "gamma", "pearce", relative)
--> ]()[939](file:///~/Articles/reviews/ReScience-Misiek/sources/grid_search.py?line=938)[ df_rodrigo,data2,bin22,bin21 = plot_single_perfs(res_df, size_plot, "inv_temp", "srlr", "rodrigo", relative)
    ]()[940](file:///~/Articles/reviews/ReScience-Misiek/sources/grid_search.py?line=939)[ _,data5,bin52,bin51 = plot_single_perfs(res_df, size_plot, "qlr", "gamma", "rodrigo", relative)
    ]()[942](file:///~/Articles/reviews/ReScience-Misiek/sources/grid_search.py?line=941)[ #_,data3,bin32,bin31 = plot_single_perfs(res_df, size_plot, "inv_temp", "srlr", "product", relative)
    ]()[943](file:///~/Articles/reviews/ReScience-Misiek/sources/grid_search.py?line=942)[ #_,data6,bin62,bin61 = plot_single_perfs(res_df, size_plot, "qlr", "gamma", "product", relative)

File ~/Articles/reviews/ReScience-Misiek/sources/grid_search.py:806, in plot_single_perfs(df, bins_nbr, dim1_name, dim2_name, expe, relative)
    ]()[804](file:///~/Articles/reviews/ReScience-Misiek/sources/grid_search.py?line=803)[ elif expe == "rodrigo":
    ]()[805](file:///~/Articles/reviews/ReScience-Misiek/sources/grid_search.py?line=804)[     if relative:
--> ]()[806](file:///~/Articles/reviews/ReScience-Misiek/sources/grid_search.py?line=805)[         data[dim1][dim2] = df["se_cluster_100_rodrigo_mean_relative"][indexes].min()
    ]()[807](file:///~/Articles/reviews/ReScience-Misiek/sources/grid_search.py?line=806)[     else:
    ]()[808](file:///~/Articles/reviews/ReScience-Misiek/sources/grid_search.py?line=807)[         data[dim1][dim2] = df["se_cluster_100_rodrigo_mean_absolute"][indexes].min()

File ~/Applications/miniforge3/envs/mixedcoord/lib/python3.9/site-packages/pandas/core/frame.py:3458, in DataFrame.__getitem__(self, key)
   ]()[3456](file:///~/Applications/miniforge3/envs/mixedcoord/lib/python3.9/site-packages/pandas/core/frame.py?line=3455)[ if self.columns.nlevels > 1:
   ]()[3457](file:///~/Applications/miniforge3/envs/mixedcoord/lib/python3.9/site-packages/pandas/core/frame.py?line=3456)[     return self._getitem_multilevel(key)
-> ]()[3458](file:///~/Applications/miniforge3/envs/mixedcoord/lib/python3.9/site-packages/pandas/core/frame.py?line=3457)[ indexer = self.columns.get_loc(key)
   ]()[3459](file:///~/Applications/miniforge3/envs/mixedcoord/lib/python3.9/site-packages/pandas/core/frame.py?line=3458)[ if is_integer(indexer):
   ]()[3460](file:///~/Applications/miniforge3/envs/mixedcoord/lib/python3.9/site-packages/pandas/core/frame.py?line=3459)[     indexer = [indexer]

File ~/Applications/miniforge3/envs/mixedcoord/lib/python3.9/site-packages/pandas/core/indexes/base.py:3363, in Index.get_loc(self, key, method, tolerance)
   ]()[3361](file:///~/Applications/miniforge3/envs/mixedcoord/lib/python3.9/site-packages/pandas/core/indexes/base.py?line=3360)[         return self._engine.get_loc(casted_key)
   ]()[3362](file:///~/Applications/miniforge3/envs/mixedcoord/lib/python3.9/site-packages/pandas/core/indexes/base.py?line=3361)[     except KeyError as err:
-> ]()[3363](file:///~/Applications/miniforge3/envs/mixedcoord/lib/python3.9/site-packages/pandas/core/indexes/base.py?line=3362)[         raise KeyError(key) from err
   ]()[3365](file:///~/Applications/miniforge3/envs/mixedcoord/lib/python3.9/site-packages/pandas/core/indexes/base.py?line=3364)[ if is_scalar(key) and isna(key) and not self.hasnans:
   ]()[3366](file:///~/Applications/miniforge3/envs/mixedcoord/lib/python3.9/site-packages/pandas/core/indexes/base.py?line=3365)[     raise KeyError(key)

KeyError: 'se_cluster_100_rodrigo_mean_relative']()
```

Is there a way to fix this without losing all the simulations?

**Comment by thomasMisiek** [comment]
@vitay Yes, setting the "relative" parameter to True in the "compute_clusters_perfs(path, 100, experimental_data_pearce, experimental_data_rodrigo, relative=False)" cell, and running again the "res_df = plot_all_perfs(path, size_plot=10, relative=True)" cell should do the trick. Sorry for this inconvenience. I will update the repository.

**Comment by vitay** [comment]
@thomasMisiek Thanks, that allowed me to continue running the notebook. I attach the pdf of the notebook. It seems that the Rodrigo experiments quite failed, there was no better parameter values. I am a bit lost in all the other plots. Can you check they are what you intended? 

[Geerts Arbitrator - Egocentric MF-SR.pdf](https://github.com/ReScience/submissions/files/8149301/Geerts.Arbitrator.-.Egocentric.MF-SR.pdf)

**Comment by mstimberg** [comment]
Hi everyone. I also started running the code, but began from a different angle than @vitay . I had a few small-ish problems, and opened corresponding issues in the code repository (thomasMisiek/mixed-coordination-models#1, thomasMisiek/mixed-coordination-models#2, thomasMisiek/mixed-coordination-models#3, thomasMisiek/mixed-coordination-models#4, thomasMisiek/mixed-coordination-models#5).

**Comment by thomasMisiek** [comment]
@vitay I just checked your PDF and it looks like what I intended, with the exception of the display of rodrigo's grid-search results. I believe the rodrigo's grid-search and display methods themselves are working properly. However, nothing is displayed because datapoints are only plotted if they are associated to behavioral performances which validates a set of statistical tests. On my last execution of the code, I placed very low values of p in the source code such that only 8 sets of parameters out of 2000 validated the statistical tests. It seems that in your execution, no datapoint at all were able to validate these tests. Increasing p-values from 0.005 to 0.05, for example, should allow much more datapoints to be displayed, as with Pearce's grid-search.

I also see in your PDF that the plot_all_perfs() function did not display the three sets of parameters producing the lowest MSE, as it should have, and only printed "<IPython.core.display.HTML object>". This never happened on my machines, I will try to find a more robust and portable way to plot this HTML object on any computer.

Other than that, every cells that you executed produced the intended results for Pearce experiment as well as for Rodrigo's experiment. Nevertheless, you should ignore every results that comes after the markdown cell **2.3 Results on Pearce’s experiment with steeper decrease in P(SR)**. Nothing after this cell is related to our replication study, but is related to another paper. This includes Rodrigo's experiment (grey histograms) and Pearce's 3rd experiment (blue histograms). 

Beside the grid-search, the only part related to this replication study is the **(2. Testing the grid-search predictions: Pearce, Roberts, Good)** section. The best set of parameters found using the grid-search is defined **(2.1)**, then 100 agents simulations are performed for the control group **(2.1)** and HPC-lesioned groups **(2.2)**. The escape time of both groups are then plotted on the same figure with the **plot_pearce()** function. There is a lot of information displayed in the **(2.x)** section, the only relevant informations for the replication paper are the "Our results" plot in the **plot_pearce()** cell just before the **(2.3)** section. And also the ANOVAs on the "trial" variable for the control group**(2.1)** and lesioned group **(2.2)**, and the ANOVAs on the "group" variable in the **plot_pearce()** cell. Your results (ANOVAs and figure) seems to be coherent with those in our papers.

**Comment by thomasMisiek** [comment]
@mstimberg Ok I will check that !

**Comment by vitay** [comment]
@thomasMisiek Thanks. Would it be possible to add a simpler notebook that only deals with the results presented in the ReScience paper? It is nice to have code with a broader scope, but some readers might want to focus on Geerts' model applied to Pearce's task.

**Comment by mstimberg** [comment]
I concur with @vitay's suggestion, in particular given that these simulations take a lot of time to run. I tried running the notebook overnight on my notebook, but it failed due to a disk space issue when the results folder was filled with several GB. Could you give an estimate how much disk space is needed?
An unrelated question: there are a number of lines in the notebook annotated with comments like `# lower values of p`, but I don't see anything in the function calls that changes `p`. The most confusing are these three repeated lines:
```Python
res_df = plot_all_perfs(path, size_plot=10, relative=True) # higher values of p, compared to the next cell
res_df = plot_all_perfs(path, size_plot=10, relative=True) # lower values of p
res_df = plot_all_perfs(path, size_plot=10, relative=True) # lower values of p
```
These surely all do the same thing?

**Comment by thomasMisiek** [comment]
@vitay @mstimberg Ok, I will create a specific notebook for the replication study right now, with only cells related to Pearce experiment. Please note that out of all the notebooks, only the "Geerts Arbitrator - Egocentric MF-SR.ipynb" is currently related to this paper. I understand that it might have not been clear from the beginning, thus I will add a few lines in the README to specify the required steps for people that are only interested in this replication paper.

@mstimberg On my computer, a complete grid-search simulation for Pearce experiment generates 10 Go of data. A 100 datapoints experiment generates 400 Mo of data. It's respectively 11Go and 1Go for Rodrigo's task, which won't appear in the new notebook anyway.  Running Pearce's grid-search should take 4 to 6 hours, whereas Rodrigo's should take 10 to 12 hours. The remaining cells of the notebook should fully execute in less than one hour. 

There is indeed three cells plotting the grid-search results with the same function call `plot_all_perfs(path, size_plot=10, relative=True).` If you open the notebook without modifications, you will see that they display different results. That is because after each function call, I modified the list of p-values directly in the code. The reason for this was to show the user that modifying p-values have an effect on the grid-search results. I understand that this can be misleading for the user after running again the whole notebook, I will thus remove two of the three cells and add a comment to specify that the p-values can be found and modified in the grid-search.py module.

**Comment by thomasMisiek** [comment]
@mstimberg @vitay I just added the Geerts Replication.ipynb to the repository, it contains everything related to the paper (replication) and nothing else. I added a paragraph about it in the README. I also removed two of the three displays of the grid-search. 
@mstimberg I will solve the opened issue 1 and 2 as soon as possible, on saturday.

**Comment by mstimberg** [comment]
@thomasMisiek Thanks. No need to rush from my side, I won't be able to look into things before next Tuesday anyway.

**Comment by mstimberg** [comment]
I successfully ran the `Geerts Replication.ipynb` notebook and only encountered two small issues (thomasMisiek/mixed-coordination-models#7, thomasMisiek/mixed-coordination-models#8). The results look comparably to the values in the unchanged notebook, but not identical. I assume part of it is due to randomness in the simulations, would it be possible to fix things with a seed to get the exact same results? Regardless of this, please re-run/save the notebook. Its cells were evaluated out-of-order, and it looks as if the grid search was manually restricted to 150 instead of 2000 data points for the earlier part of the notebook, while it uses the results from a full grid search in the later parts. In the "Lesioned agents training" section, `perform_group_pearce` (or a function called by it) seems to be different from the version in the repository: in the uploaded notebook it performs a "Two-way ANOVA on trial and session" whereas when I run it, it performs two separate ANOVAs on trial and session.

> The reason for this was to show the user that modifying p-values have an effect on the grid-search results. I understand that this can be misleading for the user after running again the whole notebook, I will thus remove two of the three cells and add a comment to specify that the p-values can be found and modified in the grid-search.py module.

If the p-value cut-off is an interesting parameter to vary here, it could be added as an optional parameter to the function, maybe?

**Comment by thomasMisiek** [comment]
@mstimberg I added a seed parameter to both the `random_grid-search()` function and the `perform_group_pearce()` function. 

I am re-running the notebook again to get rid of the out-of-order cells calls, the 150 datapoints instead of 2000, and the "Two-way ANOVA on trial and session" which comes from a previous version of the program. I will also run two successive grid-search with 2000 datapoints. The first being identical to the current one in the notebook, and the second exploring only a subset of the multidimensional space from the first, to improve the accuracy of the search. I will inform you when this notebook is ready and uploaded.

I added a single p-value parameter to the function that performs the statistical analyses, so that the user can tune it.

**Comment by thomasMisiek** [comment]
@mstimberg I just pushed the new version of the Geerts_Replication notebook.

**Comment by thomasMisiek** [comment]
I have modified the PDF (parameters values and ANOVAs' results) to fit the new results of the geerts_replication notebook. I also created a "best_geerts" and "best_geerts_stochastic" option, for respectively deterministic and stochastic computing if the user chooses to use the command line instead of the notebook.

**Comment by vitay** [comment]
Thanks for the changes and the new notebook. The code runs without major problems (and much faster) and I got the following results for the deterministic case:

<img width="830" alt="Screenshot 2022-03-23 at 08 54 04" src="https://user-images.githubusercontent.com/11293653/159651684-d3514843-4396-45ef-8f54-b4de79c625e9.png">


Just a tip: add `#cython: language_level=3` at the top of each of your .pyx files to get rid of the warning:

```
FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release!
```

The tqdm progress bar did not work for me, but it is not a big deal, it probably comes from my setup.

I guess it is time to conclude the review now. Overall this is a very valuable partial replication of Geerts' model, as it fixes several issues with the published code and gets even closer to Pearce's experimental data. The goals of the replication are very well explained in the paper and the code will be useful to every researchers interested in spatial navigation and successor representations.

@rougier I recommend accepting the paper as a partial replication.

**Comment by rougier** [comment]
@vitay @mstimberg  Thanks for thorough reviews. @mstimberg Are you satisfied with latest changes?

**Comment by mstimberg** [comment]
Hi @rougier, @thomasMisiek. I am satisfied in general and happy with the various improvements, they should make running the code much more straightforward. I have one issue open in the repository that is still not addressed (thomasMisiek/mixed-coordination-models#6), but it might not be relevant for the ReScience paper (I'll let @thomasMisiek confirm). Apart from that, I was able to run everything and get the expected results, both with the notebooks and the scripts.
I therefore also recommend accepting the paper. Please note that the generated PDF still has a number of formatting issues, though: The article reference at the start is not formatted correctly in the usual "block", and the sections seem to be "on the wrong level" (e.g. `\subsection` instead of `section`), leading to the 0.1, 0.2, ... numbering. It also states "Received: 01 November 2018", but I assume this gets fixed when the other missing metadata will be added. As a final note: make sure to tag a new release and publish it on Zenodo, the PDF currently still links to https://zenodo.org/record/5854457 with the version from January.

**Comment by mstimberg** [comment]
Apologies, I forgot one minor suggestion in my previous comment: you might consider adding a footnote to the paper explaining your understanding of "replication" and "reproduction" (or simply link to the [ReScience FAQ](https://rescience.github.io/faq/)). Your manuscript is mostly about a replication, but you also briefly mention the reproduction, and there is a lot of confusion around these terms.

**Comment by thomasMisiek** [comment]
@vitay @mstimberg  Thank you for your thoughtful comments and your efforts towards improving the code and the readability of the results.

@rougier @mstimberg Yes I confirm that [https://github.com/thomasMisiek/mixed-coordination-models/issues/6](url) is not relevant for the Rescience paper. 

@mstimberg I will add a footnote to the PDF about Replication/Reproduction and then I will fix the PDF format issues you mentioned, as well as the Zenodo issue.

**Comment by rougier** [comment]
@thomasMisiek Congratulations, your paper is accepted! @vitay @mstimberg Many thanks again for efficient and useful review.

@thomasMisiek I'll proceed with publication which can take a few days, don't hesitate to remind/spam me if it's not done in the next few days.

**Comment by rougier** [comment]
@thomasMisiek Do you have a link to the article sources?

**Comment by rougier** [comment]
For publication, I would need a software heritage id. Can you check https://www.softwareheritage.org/save-and-reference-research-software/ and get sch id (it's quite easy to generate).

**Comment by thomasMisiek** [comment]
@rougier Here it is https://archive.softwareheritage.org/browse/revision/239cae046e09974d285fbb0d06c734b3a901fb5c/?origin_url=https://github.com/thomasMisiek/mixed-coordination-models

**Comment by rougier** [comment]
It's online at https://rescience.github.io/bibliography/Misiek_2022.html
